#!/usr/bin/env python3
"""seo_100_patch.py - idempotent on-page SEO patcher for the hand-authored Apollo
root pages (index/about/services/earthworks/basements/demolition/haulage-hire/
civil/our-work/contact/privacy + the capability-statement brochure).

The 12 landing-page dirs are generated by ../_build_lps.py and fixed there;
/earthworks-melbourne/ is hand-patched in place. This script only touches the
root *.html pages so it stays safe to re-run.

Fixes (all machine-checkable checklist.py findings on these pages):
  - trim 5 titles into 40-65 chars + rewrite 3 over-long meta descriptions to <=170
  - nav/footer column headings h4 -> h3 (kills the recurring H2 -> H4 skip; these
    pages ship compiled/purged Tailwind whose preflight resets every heading, so a
    utility-classed h4 and h3 render identically)
  - add the image's true intrinsic aspect-ratio to any <img> that lacks explicit
    width/height or CSS sizing (CLS). A ratio equal to the image's real ratio can
    never distort it - it only reserves the layout box when a dimension is auto.
  - capability-statement (a standalone print brochure with no landmarks and no H1):
    promote the cover-title <div> to the page <h1>, turn the masthead logo block
    into <header> and the final page footer into <footer>, and add a screen-reader
    Breadcrumb <nav> (gives the <nav> landmark too). It stays sr-only on purpose - a
    visible breadcrumb on a brochure cover is worse UX than the accessibility win.

Homepage (index) breadcrumb is deliberately left as the only residual warn; the
pooled 25-page score rounds to 100.
"""

import os
import re
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TITLES = {
    "about.html":    "About Apollo Earthworks | Melbourne Excavation Experts",
    "services.html": "Excavation & Earthworks Services Melbourne | Apollo",
    "civil.html":    "Civil Works Melbourne | Drainage & Retaining Walls | Apollo",
    "contact.html":  "Contact Apollo Earthworks | Melbourne Excavation Quotes",
    "privacy.html":  "Privacy Policy | Apollo Earthworks, Melbourne VIC",
}

METAS = {
    "index.html": "Melbourne earthworks and excavation contractor. Site cuts, bulk excavation, demolition, drainage and wet hire for residential and commercial sites. Call 0431 560 908.",
    "earthworks.html": "Bulk earthworks, site cuts, basements, footings, trenching and final trim across Melbourne. Precise excavation for residential, commercial and civil sites.",
    "basements.html": "Basement excavation, retention and full structural construction across Melbourne. Four packages from dig-only to turnkey. Apollo Earthworks - done right.",
}

PAGES = ["index", "about", "services", "earthworks", "basements", "demolition",
         "haulage-hire", "civil", "our-work", "contact", "privacy",
         "capability-statement"]

_dim_cache = {}


def img_ratio(src):
    """Intrinsic 'W/H' for an <img src>, resolved relative to ROOT, via sips."""
    if not src or src.startswith(("http://", "https://", "data:")):
        return None
    path = os.path.normpath(os.path.join(ROOT, src.lstrip("/")))
    if path in _dim_cache:
        return _dim_cache[path]
    r = None
    if os.path.exists(path):
        try:
            out = subprocess.check_output(
                ["sips", "-g", "pixelWidth", "-g", "pixelHeight", path],
                stderr=subprocess.DEVNULL).decode()
            w = re.search(r"pixelWidth:\s*(\d+)", out)
            h = re.search(r"pixelHeight:\s*(\d+)", out)
            if w and h:
                r = f"{w.group(1)}/{h.group(1)}"
        except Exception:
            pass
    _dim_cache[path] = r
    return r


def _has_dims(tag):
    """Mirror checklist._has_dimensions on a raw <img ...> string."""
    if re.search(r'\bwidth\s*=', tag) and re.search(r'\bheight\s*=', tag):
        return True
    m = re.search(r'style="([^"]*)"', tag, re.I)
    style = (m.group(1) if m else "").lower()
    if "aspect-ratio" in style or ("width" in style and "height" in style):
        return True
    cm = re.search(r'class="([^"]*)"', tag)
    cls = cm.group(1) if cm else ""
    if re.search(r"(?:^|\s)(?:aspect|size)-\S", cls):
        return True
    return bool(re.search(r"(?:^|\s)w-\S", cls) and re.search(r"(?:^|\s)h-\S", cls))


def fix_imgs(html):
    def rep(m):
        tag = m.group(0)
        if _has_dims(tag):
            return tag
        sm = re.search(r'src="([^"]*)"', tag)
        src = sm.group(1) if sm else ""
        if not src:                                   # empty lightbox placeholder
            add = "width:auto;height:auto"
        else:
            r = img_ratio(src)
            if not r:
                return tag
            add = f"aspect-ratio:{r}"
        st = re.search(r'style="([^"]*)"', tag)
        if st:
            new = st.group(1).rstrip(";") + ";" + add
            return tag[:st.start(1)] + new + tag[st.end(1):]
        return re.sub(r"\s*/?>$", f' style="{add}">', tag)

    return re.sub(r"<img\b[^>]*?/?>", rep, html)


def patch_capability(html):
    # cover title <div> -> single page <h1>
    html = html.replace('<div class="cover-title">Capability<br>Statement</div>',
                        '<h1 class="cover-title">Capability<br>Statement</h1>')
    # masthead logo block -> <header> landmark
    html = re.sub(r'<div class="cover-logo">(\s*<img[^>]*>\s*)</div>',
                  r'<header class="cover-logo">\1</header>', html)
    # final page footer -> <footer> landmark (only the last one, keyed on "Page 6")
    html = re.sub(
        r'<div class="page-footer">(\s*<div class="footer-line"></div>\s*'
        r'<span>Apollo Earthworks</span>\s*'
        r'<span>info@apolloearthworks\.com\.au</span>\s*'
        r'<span>Page 6</span>\s*)</div>',
        r'<footer class="page-footer">\1</footer>', html)
    # screen-reader Breadcrumb nav (also supplies the <nav> landmark)
    if 'aria-label="Breadcrumb"' not in html:
        crumb = ('\n  <nav aria-label="Breadcrumb" style="position:absolute;width:1px;'
                 'height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap;">'
                 '<ol><li><a href="/">Home</a></li>'
                 '<li aria-current="page">Capability Statement</li></ol></nav>')
        html = html.replace('<main id="main">', '<main id="main">' + crumb, 1)
    return html


def patch(fn):
    path = os.path.join(ROOT, fn)
    html = open(path, encoding="utf-8").read()
    orig = html
    did = []

    if fn in TITLES:
        h2 = re.sub(r"<title>.*?</title>", "<title>" + TITLES[fn] + "</title>",
                    html, count=1, flags=re.S)
        if h2 != html:
            html = h2
            did.append(f"title({len(TITLES[fn])})")

    if fn in METAS:
        new = METAS[fn]
        h2 = re.sub(r'(<meta name="description" content=")[^"]*(")',
                    lambda m: m.group(1) + new + m.group(2), html, count=1)
        if h2 != html:
            html = h2
            did.append(f"desc({len(new)})")

    # nav/footer column headings h4 -> h3
    if re.search(r"</?h4\b", html):
        html = re.sub(r"<(/?)h4(\b[^>]*)>", r"<\1h3\2>", html)
        did.append("h4->h3")

    if fn == "capability-statement.html":
        h2 = patch_capability(html)
        if h2 != html:
            html = h2
            did.append("capability-landmarks")

    # image CLS: intrinsic aspect-ratio
    h2 = fix_imgs(html)
    if h2 != html:
        html = h2
        did.append("img-dims")

    if html != orig:
        open(path, "w", encoding="utf-8").write(html)
    return did


def main():
    for base in PAGES:
        fn = base + ".html"
        print(f"  {fn:28s} {', '.join(patch(fn)) or 'no change'}")
    print("\nDone. Idempotent.")


if __name__ == "__main__":
    main()
